
ALTER TABLE invites
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
    USING created_at AT TIME ZONE 'UTC';

ALTER TABLE instance_invites
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
    USING created_at AT TIME ZONE 'UTC';

ALTER TABLE members
    ALTER COLUMN joined_at TYPE TIMESTAMP WITH TIME ZONE
    USING joined_at AT TIME ZONE 'UTC';

ALTER TABLE messages 
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE 
    USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN edited_at TYPE TIMESTAMP WITH TIME ZONE 
    USING edited_at AT TIME ZONE 'UTC';

ALTER TABLE message_reactions
    ALTER COLUMN react_ts TYPE TIMESTAMP WITH TIME ZONE
    USING react_ts AT TIME ZONE 'UTC';

ALTER TABLE users
    ALTER COLUMN premium_since TYPE TIMESTAMP WITH TIME ZONE
    USING premium_since AT TIME ZONE 'UTC',
    ALTER COLUMN last_session TYPE TIMESTAMP WITH TIME ZONE
    USING last_session AT TIME ZONE 'UTC';

ALTER TABLE user_subscriptions
    ALTER COLUMN canceled_at TYPE TIMESTAMP WITH TIME ZONE
    USING canceled_at AT TIME ZONE 'UTC',
    ALTER COLUMN period_start TYPE TIMESTAMP WITH TIME ZONE
    USING period_start AT TIME ZONE 'UTC',
    ALTER COLUMN period_end TYPE TIMESTAMP WITH TIME ZONE
    USING period_end AT TIME ZONE 'UTC';
